/**
 * Joukowsky Hydraulic Transient (Water Hammer) Engine
 * Models acoustic pressure waves generated by rapid valve shut-off:
 * Delta_P = rho * a * Delta_v
 * Compares unprotected sudden shut-off vs intelligent VFD soft deceleration.
 */
export class WaterHammerEngine {
    constructor() {
        this.rho = 1000.0; // kg/m^3
        this.a = 1200.0; // Acoustic wave speed in water pipe (m/s)
        this.pipeLength = 150.0; // Pipe length (m)
        this.pipeDiameter = 0.075; // Pipe diameter (m, DN80)
        this.pipeArea = (Math.PI * (this.pipeDiameter ** 2)) / 4.0; // m^2

        this.pipeRatingBar = 16.0; // PN16 pipe pressure rating (Bar)
        this.baselinePressureBar = 5.0; // Steady state pressure (Bar)
        this.peakSurgeBar = 5.0;
        this.isSurgeActive = false;

        this.historyLength = 100;
        this.pressureTrace = new Float32Array(this.historyLength).fill(5.0);
        this.simTime = 0.0;
    }

    /**
     * Trigger a valve shut-off transient
     * @param {number} flowM3PerHour - Initial steady-state flow
     * @param {boolean} useSoftRamp - Whether Grundfos intelligent soft ramp is engaged
     */
    triggerValveClosure(flowM3PerHour, useSoftRamp = false) {
        let vInitial = (flowM3PerHour / 3600.0) / this.pipeArea; // m/s
        let tc = useSoftRamp ? 2.5 : 0.08; // Closure time (seconds)
        let tr = (2 * this.pipeLength) / this.a; // Pipe reflection time ~0.25s

        let deltaP_Pa;
        if (tc <= tr) {
            // Instantaneous Joukowsky shockwave
            deltaP_Pa = this.rho * this.a * vInitial;
        } else {
            // Slow closure: Allievi equation
            deltaP_Pa = (2 * this.rho * this.pipeLength * vInitial) / tc;
        }

        let deltaP_Bar = deltaP_Pa / 1.0e5;
        this.peakSurgeBar = this.baselinePressureBar + deltaP_Bar;
        this.isSurgeActive = true;
        this.simTime = 0.0;
    }

    step(dt) {
        if (!this.isSurgeActive) {
            // Steady state
            this.pushSample(this.baselinePressureBar + (Math.random() * 0.1 - 0.05));
            return;
        }

        this.simTime += dt;
        let decay = Math.exp(-this.simTime * 2.5);
        let period = (4 * this.pipeLength) / this.a; // Fundamental acoustic oscillation
        let osc = Math.sin((2 * Math.PI / period) * this.simTime);

        let deltaP = (this.peakSurgeBar - this.baselinePressureBar) * decay * osc;
        let currentP = this.baselinePressureBar + deltaP;
        this.pushSample(currentP);

        if (this.simTime > 3.0) {
            this.isSurgeActive = false;
        }
    }

    pushSample(val) {
        for (let i = 0; i < this.historyLength - 1; i++) {
            this.pressureTrace[i] = this.pressureTrace[i + 1];
        }
        this.pressureTrace[this.historyLength - 1] = val;
    }
}
